Launch db from bootstrap for running integration tests

diff --git a/docker/assets/with_bootstrap b/docker/assets/with_bootstrap
--- a/docker/assets/with_bootstrap
+++ b/docker/assets/with_bootstrap
@@ -1,31 +1,66 @@
 #!/bin/bash
 
+
+launch_db () {
+    local pgdata="${1:-${HOME}/srv/postgresql}"
+    local dbuser="${2:-odc}"
+    local bin=/usr/lib/postgresql/10/bin
+
+    [ -e "${pgdata}/PG_VERSION" ] || {
+        sudo -u postgres "${bin}/initdb" -D "${pgdata}" --auth-host=md5 --encoding=UTF8
+    }
+
+    sudo -u postgres "${bin}/pg_ctl" -D "${pgdata}" -l "${pgdata}/pg.log" start
+
+    sudo -u postgres createuser --superuser "${dbuser}"
+    sudo -u postgres createdb "${dbuser}"
+    sudo -u postgres createdb datacube
+    sudo -u postgres createdb agdcintegration
+}
+
 [ -n "${GDAL_DATA:-}" ] || {
     export GDAL_DATA=$(gdal-config --datadir)
 }
 
 # Become `odc` user with UID/GID compatible to datacube-core volume
 #  If Running As root
+#    launch db server
 #    If outside volume not owned by root
-#       create user `odc` with compatible UID/GID
+#       change `odc` to have compatible UID/GID
 #       re-exec this script as odc user
 
 [[ $UID -ne 0 ]] || {
+    launch_db /srv/postgresql odc > /dev/null 2> /dev/null || {
+        echo "WARNING: Failed to launch db integration tests might not run"
+    }
+
     target_uid=$(stat -c '%u' .)
     target_gid=$(stat -c '%g' .)
 
     [[ $target_uid -eq 0 ]] || {
-        groupadd --gid "${target_gid}" odc
-        useradd --uid "${target_uid}" \
-                --gid "${target_gid}" \
-                --create-home \
-                --shell /bin/bash odc
-
+        groupmod --gid "${target_gid}" odc
+        usermod --gid "${target_gid}" --uid "${target_uid}" odc
+        chown -R odc:odc /home/odc/
         exec sudo -u odc -H bash "$0" "$@"
     }
 }
 
 dc_config_render.py auto
+cat <<EOL > $HOME/.datacube_integration.conf
+[datacube]
+db_hostname:
+db_database: agdcintegration
+index_driver: default
+
+[s3aio_env]
+db_hostname:
+db_database: agdcintegration
+index_driver: s3aio_index
+
+[no_such_driver_env]
+db_hostname:
+index_driver: no_such_driver
+EOL
 
 env="${PYENV:-/env}"
 
@@ -35,7 +70,6 @@ if [ -e "${env}/bin/activate" ]; then
     }
 fi
 
-[ -z "$@" ] || {
+[ -z "${1:-}" ] || {
     exec "$@"
 }
-
